### ISSUE TITLE
Gestion des régions d'Outre-mer

### ISSUE THREAD

**Issue by synyster0fa7x** [rleger/covidrea#1]
Est-ce envisagé/able d'ajouter les régions d'Outre-Mer sur l'application ?

**Comment by synyster0fa7x** [comment]
Réponse de Romain : 

> En effet on peut tout à fait ajouter les régions d’outre-mer au formulaire de la page d’accueil cependant pour l’instant nous avons prévu d’ouvrir uniquement sur la Bourgogne Franche-Comté au début pour pouvoir procéder aux ajustements nécessaires et grandir progressivement. (Régions du select de la page d’accueil dans config/covidrea.php). Il est évident qu’une fois que le site sera national les DOM devront en faire partie.

**Comment by rleger** [comment]
J'ai ajouté les DOM sur le formulaire de la page d'accueil pour l'instant
