### ISSUE TITLE
Faille de sécurité : je peux modifier les lits d'un service que je ne gère pas

### ISSUE THREAD

**Issue by nyroDev** [rleger/covidrea#10]
Lors de mon inscription, je n'ai demandé que 3 services sur les 10 de l'établissement existant.

Lorsque je suis connecté et que je clique sur "Modifier mes lits disponibles", j'atterris sur la page
https://covid-moi-un-lit.com/user/120/service
où je vois mes services et la possibilité de modifier les chiffres.

En modifiant l'URL pour être 
https://covid-moi-un-lit.com/user/119/service  
Les services affichés ne sont pas les mêmes (mais du même établissement).
Les 2 premiers que je vois sont des services auxquels j'ai accès, mais pas le dernier.

J'ai testé, j'ai pu modifier les chiffres de cet autre service.

Plusieurs choses :  
1. Modifier pour ne pas avoir d'ID dans l'URL et se baser uniquement sur l'utilisateur connecté
2. Existe-t-il un log des modifications effectuées pour savoir qui a modifié quoi ?

**Comment by rleger** [comment]
Tout à fait, il est prévu d'implémenter cette fonctionnalité avec les Gates et Policies
https://laravel.com/docs/7.x/authorization
Si tu veux t'y attaquer, sinon je ferai

On gardera l'id car ce n'est pas un pb a partir du moment ou les Gates seront implémenté
Il y a un package qui track tout ("owen-it/laravel-auditing":,)

**Comment by rleger** [comment]
idem https://github.com/rleger/covidrea/issues/12

**Comment by bdahon** [comment]
PR ici #29
