### ISSUE TITLE
Dashboard sur mobile , affichage du filtre par rayon kilométrique 

### ISSUE THREAD

**Issue by tcarpentier** [rleger/covidrea#13]
Lorsque j'affiche le site en mode mobile, sur le dashboard, il n'est pas possible de filter les résultats suivant un rayon kilométriques
![Screenshot_2020-03-27 Laravel](https://user-images.githubusercontent.com/763778/77806185-40993d80-7084-11ea-9c07-a4d9ad93e993.png)

**Comment by rleger** [comment]
Merci, c'est en effet voulu, cette fonctionnalité n'est pas essentielle, on verra pourquoi pas pour un Dropdown a l'occasion mais absolument pas prioritaire
