### ISSUE TITLE
Nombre de places, Nombre de places disponibles et bientôt disponibles limités à 100 max

### ISSUE THREAD

**Issue by tcarpentier** [rleger/covidrea#14]
J'imagine qu'il n'y a pas beaucoup d'hopitaux avec un si grand nombre de lits en réanimation, donc 100 parait-être un bon chiffre, mais est-ce voulu ? 

Sur mobile,  si je rentre un chiffre plus grand ( exemple 101 ) et que je clique sur "Enregister", je n'ai pas de message d'erreur. Il faut que je change le focus sur un autre champ pour voir le champ précédent en erreur. 

Sur un ordinateur, j'ai bien un message d'erreur m'indiquant de renseigner une valeur inférieure à 100

**Comment by nyroDev** [comment]
déjà mentionné dans #7

**Comment by rleger** [comment]
La limite à 100 est voulue.

Sur iOS la il est impossible de mettre + que 100 avec le max sur le tag html5, est-ce que ton tel est android ?
