### ISSUE TITLE
La pagination sur mobile ne fonctionne pas

### ISSUE THREAD

**Issue by tcarpentier** [rleger/covidrea#15]
- Afficher le site sur mobile
- Aller dans mes lits disponibles
- Aller tout en bas de la liste 
- Cliquer sur "Next"

-> la page suivante ne s'affiche pas, en effet le lien est : "http://localhost:8000/etablissements#"

**Comment by nyroDev** [comment]
déjà mentionné dans #8 mais un peu plus de détails ici.

**Comment by rleger** [comment]
merci, on centralise sur #8
