### ISSUE TITLE
Installer tracker stats

### ISSUE THREAD

**Issue by fixo94** [rleger/covidrea#17]
Google analytics ou autre, permettra d'avoir des stats de connexion notamment géographique (anticipation de demande par région ?)

**Comment by rleger** [comment]
Google anatlytics est installé

**Comment by synyster0fa7x** [comment]
Je rouvre le ticket.
Je ne sais pas si Google Analytics est une bonne idée. Cela impose des mentions légales claires sur le sort des données récoltées via le cookie.

J'ai une solution open source utilisée pour https://simulateur-municipales.fr/#/ qui nous a permis de ne pas mettre en place de bandeau d'avertissement de cookie (et les données sont confinées sur une de mes machines et non aux US).

**Comment by fixo94** [comment]
Ok Romain en fait c'est sur la homepage que le tracker n'est pas installé. Je te laisse trancher avec Antho pour GA ou autre soluce ensuite.

**Comment by rleger** [comment]
Ok merci, en effet il n’était pas sur la homepage. C’est fait.

On va garder analytics je mettrai le message cookie. Merci

**Comment by fixo94** [comment]
Ok thks !
