### ISSUE TITLE
Modification établissements / création services

### ISSUE THREAD

**Issue by rleger** [rleger/covidrea#27]
Je n'ai pas encore développé les fonctionnalités de ces routes qui sont destinés a l'administrateur de l'établissement (qui est `etablissement.user_id`)

```

// Gestion des établissements
Route::get('user/{user}/etablissement/', 'UserEtablissementController@index')->name('user.etablissement.index');
Route::get('user/{user}/etablissement/{etablissement}/edit', 'UserEtablissementController@edit')->name('user.etablissement.edit');
Route::patch('user/{user}/etablissement/{etablissement}/update', 'UserEtablissementController@update')->name('user.etablissement.update');


```

Il s'agit de permettre à un utilisateur de modifier les données d'un établissement (nom, type). Les autres champs = l'adresse, long et lat ne doivent pas changer donc inutile de se compliquer la vie.

Il faut surtout que cet **utilisateur puisse CRUD des services** qui sont liés à cet établissement sur cette page.

Concrètement dans cette crise, de nouveaux services vont être affectés par les établissements, ce sera l'administrateur de l'établissement qui pourra interagir.

Il faut qu'il reste toujours au minimum 1 service et donc ne pas autoriser la suppression du dernier service par exemple.

L'idée initiale est de ne pas utiliser de JS a ce stade. (dans un 2eme temps il pourrait être question de faire une api et une SPA mais nous n'en sommes pas la).

**Comment by rleger** [comment]
Je peux aider pour l'UI. J'utilise tailwind css
https://tailwindcss.com/

J'ai des composants tout fait qui sont bien utiles
https://tailwindui.com/components

**Comment by bdahon** [comment]
J'ai fait une PR avec juste l'update du type et du nom. @rleger  Tu voulais aussi pouvoir rajouter et supprimer un service depuis cet écran ?
