### ISSUE TITLE
Quick command (type artisan command) to import json file into etablissement et user DB.

### ISSUE THREAD

**Issue by rleger** [rleger/covidrea#38]

**Comment by rleger** [comment]
[liste ETS REA covid BCF.xlsx](https://github.com/rleger/covidrea/files/4398804/liste.ETS.REA.covid.BCF.xlsx)

**Comment by bdahon** [comment]
@rleger  Il n'y a que 13 établissements dans cette feuille. J'ai lu sur internet que plus de 100 établissements sont maintenant candidats. Je me trompe ?

**Comment by bdahon** [comment]
En regardant de plus près la feuille Excel, j'imagine qu'elle a été restreinte aux seuls établissements de la région

**Comment by nyroDev** [comment]
Qu'est-ce qui doit être mis pour le champ type de l'établissement ? (choix possibles : public, prive ou temporaire)

Concernant la région, s'agit-il d du département (Doubs, Côte D'or, etc) ou de "Bourgogne Franche-Comté ?

Les informations qui seraient perdues pendant ce transfert :
1. Niveau de mobilisation : à ajouter dans la BDD ? 
2. Tous les emails autres que Mail direction.
3. Tous les téléphones, qui sont enregistré au niveau des services aujourd'hui.

Est-ce qu'on accepte de perdre ces données ou le modèle est à modifier ?

**Comment by rleger** [comment]
type établissement oui c'est un de ces 3
CHU hopitaux = public
clinique = privé
temporaire ce sera les hopitaux de campagne, y'en a pas

Pour région c'est Bourgogne franche comté par ex

oui en effet.

1. pas grave
2. pas grave
3. pas grave

Par contre ce qu'on peut faire c'est créer un champ "autres_info" qui soit json nullable et collationner le reste dedans.. on fera une manip si besoin

**Comment by bdahon** [comment]
Première PR #43
