### ISSUE TITLE
Permettre d'importer des emails au format "nom" <email@domain.com> 

### ISSUE THREAD

**Issue by rleger** [rleger/covidrea#39]
Lors de l'importation des mails, le format attendu est mail1, mail2 ou séparé par un ;
Il faudrait que les directeurs puissent copier/coller depuis les mails de leur messagerie qui en général sortent des choses type "nom" <email@domain.com> 
On pourrait d'ailleurs ajouter une colone NOM a la table invite (sans le rendre obligatoire) et préremplir le champ s'il n'est pas vide dans la vue finalize.blade.

L'importation des mails est dans InviteController @process.

Bonus extraire tout ca dans une class
Bonus write unit tests for that

(désolé pour ce code affreux.. mais dans l'urgence :) )

**Comment by rleger** [comment]
Ne fonctionne pas

**Comment by nyroDev** [comment]
La solution se trouve ici je pense : https://stackoverflow.com/questions/14010875/extract-email-and-name-with-regex

**Comment by nyroDev** [comment]
Je PR dans quelques minutes

**Comment by bdahon** [comment]
J'ai également fait une PR mais uniquement pour le front #45
