### ISSUE TITLE
Envoi du mail aux chefs d'établissement les invitant à entrer la liste d'uilisateurs

### ISSUE THREAD

**Issue by rleger** [rleger/covidrea#40]
Une fois que la table établissement sera saisie nous pourrons commencer a inviter les chefs d'établissements (etablissement.user_id) par email.

Il faudrait écrire ce job (la faire avec un job permet de le mettre en Queue plus facilement), 

Si pas familier il existe une commande : 
```
php artisan make:job Nomdujob
```

Ce job va envoyer un email aux chefs d'établissement les invitant a nous rejoindre en cliquant sur un lien (/invite/{token}). Je vais demander a Vincent de faire le mail si possible.
Pour le mail en lui meme on utilise le template Markdown qui nous simplifie la vie
https://laravel.com/docs/7.x/mail#generating-markdown-mailables

Il faudra aussi un tracking des mails et communications envoyés (pourquoi pas un modèle Notification (ManyToMany) avec type {email, sms..}, timestamps, title: {invitation_initiale, relance_invitation_1, .... })
comme ca lorsqu'on ouvrira a d'autres région on ne renverra pas le mail a ceux qui l'ont déjà eut.

**Comment by nyroDev** [comment]
Est-ce qu'il y a un rapport entre ce nouveau "job" et le "job" existant `InviteNewUsersByEmail` ?  
Car il me semble que ce "job" créer des liens vers l'URL d'invite.

Est-ce que des éléments de ce "job" existante doivent être utiliser pour s'en inspirer ? (notamment pour l'envoi de l'email)

**Comment by rleger** [comment]
oui on peut s'en inspirer, sauf que c'est affreux ce que j'ai fait car ce job est responsable de pleins de trucs :(

mais l'idée c'est d'avoir une commande (pas besoin d'UI) pour envoyer le mail initial aux chefs d'établissement. Le fait de déléguer à des JOB permet de le mettre en queue redis.

Au pire on reste dans le moche et tu duplique pour ca.. 

Il faudra aussi voir pour enregistrer les comms.. dans une table "Notifications" par exemple ou on enregistre ce qu'on envoie.. mais on peut voir apres
