### ISSUE TITLE
Afficher les établissement correspond au rayon sur le tableau de bord ?

### ISSUE THREAD

**Issue by nyroDev** [rleger/covidrea#5]
1. Aller sur le tableau de bord
2. On voit afficher des chiffres de lits dans le rayon sélectionné
3. Lorsqu'on clique, on arrive sur la liste des établissements sans limitation de rayon

Je peux comprendre à la limite d'afficher tous les établissements, ils sont ordonnés par distance.

Mais pourquoi ne pas afficher la liste filtrée directement en dessous des chiffres du dashboard ?

**Comment by rleger** [comment]
On peut en effet, l'idée était de faire attention a ne pas faire trop de requêtes ou une requête massive sur la page d'accueil qui n'est pas la + importante mais celle sur laquelle on arrive et donc sur laquelle on attends beaucoup de trafic .
Elle donne un état des lieux, en terme de fonctionnalité la liste des établissement n'est pas suffisante, il faut tout ce qui est affiché sur la page état des lits donc..
