### ISSUE TITLE
Fix cancel button

### ISSUE THREAD

**Issue by rleger** [rleger/covidrea#51]
I would like the cancel button on the views/service/edit.blade page
to go back to a previous page.. not a specific url depending on where you're coming from

Stackoverflowed it and found window.location... 
ok
but it submits the form (default behaviour), so inserted preventDefault()

anyway it's not working :)

**Comment by fixo94** [comment]
Je vois dans le code que tu as mis un window.history.back().
 Issue à closer ?

**Comment by rleger** [comment]
oui merci
