### ISSUE TITLE
UX / lien recherche un lit & login

### ISSUE THREAD

**Issue by fixo94** [rleger/covidrea#55]
Pour ceux qui n'ont pas encore de login / pass : mettre un lien vers le form d'inscription
"pas encore inscrit ?"

**Comment by rleger** [comment]
Oui mais pas sous forme d'inscription puise nous fonctionnons uniquement sur invitation (pour l'instant)
cf l'encart violet.
J'ai vu ta PR je voudrais merger mais en fait ce n'est pas une "inscription" comme une SAAS mais pour l'instant plutot "manifestez votre intéret".. et ca oui !! 

tu peux changer ? 
tks

**Comment by fixo94** [comment]
C'est en place :)

**Comment by kammor** [comment]
l'issue peut être fermée du coup ?
