### ISSUE TITLE
Donner un statut superuser a certains utils

### ISSUE THREAD

**Issue by rleger** [rleger/covidrea#57]
Certains utils (comme moi et vincent par ex) vont avoir besoin de fonctions d'administrateur. 
Nous n'avons a ce stade pas besoin d'un systeme complexe de role mais juste un champ role dans la table utile et peut être un scope dans User model

on fera les modifs sur la BD inutile de prévoir ca en UI

**Comment by samo9789** [comment]
Je prends cette issue

**Comment by samo9789** [comment]
pull request : https://github.com/rleger/covidrea/pull/59
