### ISSUE TITLE
Créer une page revue de presse

### ISSUE THREAD

**Issue by fixo94** [rleger/covidrea#61]
v1 : rapide avec liste des articles 
-> Date article
-> Nom du média (les echos, macommune, ..)
-> Titre article
-> Lien vers article
v2 : idem mais administrable en BO

Place un lien dans le footer vers la page créée

**Comment by rleger** [comment]
moi je serai  partant pour qu’on ajoute une section a notre landing page plutot qu’une page séparé

**Comment by fixo94** [comment]
Disons que si on a beaucoup d'articles la landing va être vite chargée.
On peut faire une remontée des 3 derniers articles (ou sélection de 3 articles) sur la HP + page de listing avec tous les articles.
