### ISSUE TITLE
Email de confirmation

### ISSUE THREAD

**Issue by rleger** [rleger/covidrea#66]
Quand on invite des utilisateurs (table invite) depuis la console du directeur d'établissmeent, une fois les invitations parties, on lui dit qu'on va lui envoyer un mail de confirmation (au directeur)

-> il faudrait créer un mail rapide disant quelquechose comme : 
Nous avons envoyé un email aux utilisateurs suivants (adresses email) pour les inviter à nous rejoindre

**Comment by bdahon** [comment]
PR #82
