### ISSUE TITLE
develop et master ont divergé car certaines PRs ont directement étaient mergées dans master.

### ISSUE THREAD

**Issue by bdahon** [rleger/covidrea#84]

**Comment by kammor** [comment]
Bien vu ! Ma faute, désolé.

Pour résoudre simplement le soucis on peut merger la branche & la pousser. Pour merger :
`git checkout master
git pull -p
git checkout develop
git merge master
`
Si Romain/toi préférez éviter un git push sur develop, je ferais une PR de revert.

**Comment by rleger** [comment]
OK, je regarde pour résoudre
