### ISSUE TITLE
Améliorations par rapport à l"utilisateur

### ISSUE THREAD

**Issue by nyroDev** [rleger/covidrea#9]
1. Ajouter la possibilité de modifier son adresse email (avec process de validation via l'ancienne et la nouvelle adresse ?)
2. Ajouter la possibilité de modifier son mot de passe
3. La page de réinitialisation de mot de passe permet de changer l'adresse email, pourquoi ?
4. La page de réinitialisation mets dans les value des password l'adresse email, ils devraient être vide
5. Le message d'erreur lors du missmatch de mot de passe devrait être "Le champ de confirmation **du** mot de passe ne correspond pas." (le du est manquant)
6. Après avoir utiliser un lien de réinitialisation de mot de passe, l'indication que le jeton est invalide devrait être fait avant d'afficher le formulaire.

**Comment by rleger** [comment]
je pense que tu as cliqué sur le mauvais mail (mail d'invitation initial et non le mail de réinitialisation du mot de passe).

**Comment by nyroDev** [comment]
Non, c'est bien l'email de renouvellement de mot de passe
